sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic

arch:
 - amd64
 - ppc64le

compiler:
  - clang
  - gcc
script: "./.travis/build"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtinyxml-dev
matrix:
  allow_failures:
    - compiler: clang
